name: GitHub Pages

on:
  push:
    branches:
      - main  # Or 'master', depending on your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7 # You can use any Ruby version you prefer

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build and deploy
        run: |
          bundle exec jekyll build
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git add -A
          git commit -m 'Deploy Jekyll site'
          git push origin `git rev-parse --abbrev-ref HEAD`:gh-pages
